import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import styles from "@/styles/styles.module.css"

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={`${inter.className} ${styles.allGeneral}`}>
          {children}
        </body>
    </html>
  )
}
