// import type { Metadata } from "next";
'use client'
import "../globals.css";
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react";
import styles from "@/styles/styles.module.css"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={`${inter.className} ${styles.allGeneral}`}>
        <SessionProvider>
          {children}
        </SessionProvider>
        </body>
    </html>
  )
}
