import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbarReg";
import Footer from "@/components/footer";
import DashboardHero from "@/components/dashboardHero";
import styles from "@/styles/styles.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beranda Akip BPMSPH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
          <header className={styles.mainHeader}>
            <Navbar />
            <DashboardHero />
          </header>

          <main className={styles.mainContainer}>{children}</main>

          <Footer />
      </body>
    </html>
  );
}
