'use client'
// import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbarReg";
import Footer from "@/components/footer";
import DashboardHero from "@/components/dashboardHero";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <header className="main-header">
            <Navbar />
            <DashboardHero />
          </header>

          <main className="main-container">{children}</main>

          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
