import type { Metadata } from "next";
import "../globals.css";
import AdminNavbar from "./components/adminNavbar";
import AdminSidebar from "./components/adminSidebar";
import { Epilogue } from "next/font/google";

const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}
      >
        <AdminNavbar/>
        <AdminSidebar/>

        <div className="p-8 ml-64 mt-14">
        {children}
        </div>
        
      </body>
    </html>
  );
}
