// import type { Metadata } from "next";
"use client";
import AdminNavbar from "./components/adminNavbar";
import AdminSidebar from "./components/adminSidebar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <AdminNavbar />
          <AdminSidebar />

          <div className="p-8 ml-64 mt-14">{children}</div>
      </body>
    </html>
  );
}
