// import type { Metadata } from "next";
"use client";
import "../globals.css";
import AdminNavbar from "./components/adminNavbar";
import AdminSidebar from "./components/adminSidebar";
import { Epilogue } from "next/font/google";
import { SessionProvider } from "next-auth/react";

const epilogue = Epilogue({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <SessionProvider>
          <AdminNavbar />
          <AdminSidebar />

          <div className="p-8 ml-64 mt-14">{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
