// import type { Metadata } from "next";
"use client";
import { SessionProvider } from "next-auth/react";
import "../../globals.css";
import SidebarUser from "@/components/sidebarUser";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <main className="main-container lke-filling">
        <SidebarUser />

        {children}
      </main>
    </SessionProvider>
  );
}
