import type { Metadata } from "next";
import "../../globals.css";
import SidebarUser from "@/components/sidebarUser";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="main-container lke-filling">
        <SidebarUser />

        {children}
    </main>
  );
}
